language: java
jdk:
  - oraclejdk8
  - oraclejdk11
  - openjdk10
  - openjdk11
script:
  - mvn clean package
env:
  global:
    - CODECOV_TOKEN=3bdb66f8-e0a0-45ac-884e-b0692af0cc4d

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - echo "build successfully"

after_failure:
  - echo "build is failed"

notifications:
  email: false

